ENABLE SERVER 'server1' OPTIONS {tags: ['eu']}
ALTER SERVER 'server1' SET OPTIONS {tags: ['us']}
DROP SERVER 'server1'
SHOW SERVERS
SHOW SERVERS YIELD name, address
DEALLOCATE DATABASES FROM SERVER 'server1'
REALLOCATE DATABASES
DRYRUN DEALLOCATE DATABASES FROM SERVERS 'server1', 'server2'
TERMINATE TRANSACTIONS 'db-transaction-123'
TERMINATE TRANSACTIONS
RENAME ROLE admin TO superadmin
RENAME ROLE admin IF EXISTS TO superadmin
RENAME USER alice TO bob
RENAME USER alice IF EXISTS TO bob
RENAME SERVER 'old' TO 'new'
