CALL { MATCH (n) RETURN n } IN TRANSACTIONS
CALL { MATCH (n) RETURN n } IN TRANSACTIONS OF 100 ROWS
CALL { MATCH (n) RETURN n } IN TRANSACTIONS ON ERROR CONTINUE
CALL { MATCH (n) RETURN n } IN TRANSACTIONS ON ERROR BREAK
CALL { MATCH (n) RETURN n } IN TRANSACTIONS ON ERROR FAIL
CALL { MATCH (n) RETURN n } IN TRANSACTIONS REPORT STATUS AS s
CALL { MATCH (n) RETURN n } IN TRANSACTIONS OF 500 ROWS ON ERROR CONTINUE REPORT STATUS AS s
CALL { CREATE (n:Person) } IN TRANSACTIONS OF 1 ROW
