CREATE COMPOSITE DATABASE fabric
CREATE COMPOSITE DATABASE fabric IF NOT EXISTS
CREATE DATABASE mydb WAIT 30 SECONDS
CREATE DATABASE mydb TOPOLOGY 2 PRIMARIES 1 SECONDARY
ALTER DATABASE neo4j SET ACCESS READ ONLY
ALTER DATABASE neo4j SET TOPOLOGY 3 PRIMARIES
ALTER DATABASE neo4j SET OPTION txLogRetention '2 days'
DROP DATABASE mydb DUMP DATA
DROP DATABASE mydb DESTROY DATA WAIT
DROP COMPOSITE DATABASE fabric IF EXISTS
START DATABASE mydb WAIT
STOP DATABASE mydb NOWAIT
CREATE ALIAS remote FOR DATABASE neo4j AT 'neo4j://server:7687' USER admin PASSWORD 'secret'
CREATE ALIAS local FOR DATABASE neo4j
DROP ALIAS remote IF EXISTS FOR DATABASE
ALTER ALIAS remote SET DATABASE TARGET otherdb
SHOW ALIASES FOR DATABASE
