SHOW DATABASES;
SHOW DATABASE mydb;
SHOW DEFAULT DATABASE;
CREATE DATABASE mydb;
CREATE DATABASE mydb IF NOT EXISTS;
CREATE OR REPLACE DATABASE mydb;
DROP DATABASE mydb;
DROP DATABASE mydb IF EXISTS;
START DATABASE mydb;
STOP DATABASE mydb