SHOW ALL PRIVILEGES;
SHOW ROLE myrole PRIVILEGES;
SHOW USER alice PRIVILEGES;
SHOW USER PRIVILEGES;
GRANT ACCESS ON DATABASE mydb TO myrole;
GRANT TRAVERSE ON GRAPH mydb TO myrole;
GRANT READ {*} ON GRAPH mydb TO myrole;
GRANT MATCH {*} ON GRAPH mydb TO myrole;
GRANT WRITE ON GRAPH mydb TO myrole;
GRANT ALL DATABASE PRIVILEGES ON DATABASE mydb TO myrole;
GRANT ALL GRAPH PRIVILEGES ON GRAPH mydb TO myrole;
GRANT ROLE MANAGEMENT ON DBMS TO myrole;
DENY ACCESS ON DATABASE mydb TO myrole;
REVOKE ACCESS ON DATABASE mydb FROM myrole;
REVOKE GRANT ACCESS ON DATABASE mydb FROM myrole;
REVOKE DENY ACCESS ON DATABASE mydb FROM myrole