GRANT ROLE admin TO alice
REVOKE ROLE admin FROM alice
GRANT ALL PRIVILEGES ON DBMS TO admin
GRANT ACCESS ON DATABASE neo4j TO reader
GRANT TRAVERSE ON GRAPH * TO reader
GRANT READ {*} ON GRAPH neo4j NODES * TO reader
GRANT MATCH {name, age} ON GRAPH neo4j NODES Person TO reader
GRANT WRITE ON GRAPH neo4j TO writer
GRANT CREATE INDEX ON DATABASE neo4j TO admin
GRANT DROP CONSTRAINT ON DATABASE * TO admin
GRANT CREATE NEW NODE LABELS ON DATABASE * TO creator
GRANT EXECUTE PROCEDURE apoc.* ON DBMS TO admin
GRANT CREATE ON DBMS TO admin
DENY WRITE ON GRAPH neo4j TO restricted
REVOKE GRANT TRAVERSE ON GRAPH * FROM reader
GRANT SET PASSWORD ON DBMS TO useradmin
GRANT REMOVE LABEL * ON GRAPH neo4j TO admin
GRANT NAME MANAGEMENT ON DATABASE * TO admin
