SHOW ROLES;
SHOW ALL ROLES;
SHOW POPULATED ROLES;
SHOW ROLES WITH USERS;
SHOW ALL ROLES WITH USERS;
SHOW POPULATED ROLES WITH USERS;
CREATE ROLE myrole;
CREATE ROLE myrole IF NOT EXISTS;
CREATE OR REPLACE ROLE myrole;
CREATE ROLE myrole AS COPY OF otherrole;
DROP ROLE myrole;
DROP ROLE myrole IF EXISTS