SHOW DATABASES
SHOW DATABASES YIELD name, currentStatus WHERE NOT name IN ['system'] RETURN name ORDER BY name
SHOW DATABASE neo4j YIELD name
SHOW DEFAULT DATABASE
SHOW INDEXES
SHOW INDEXES YIELD name, type
SHOW CONSTRAINTS
SHOW CONSTRAINTS YIELD *
SHOW PROCEDURES
SHOW PROCEDURES YIELD name WHERE name STARTS WITH 'db'
SHOW FUNCTIONS YIELD name, signature
SHOW CURRENT USER
SHOW TRANSACTIONS
SHOW USERS
SHOW ROLES WITH USERS
SHOW ALL PRIVILEGES
