SHOW USERS;
CREATE USER alice SET PASSWORD 'secret';
CREATE USER alice SET PASSWORD 'secret' CHANGE REQUIRED;
CREATE USER alice SET PASSWORD 'secret' CHANGE NOT REQUIRED;
CREATE USER alice SET PASSWORD 'secret' SET STATUS ACTIVE;
CREATE USER alice SET PASSWORD 'secret' SET STATUS SUSPENDED;
CREATE OR REPLACE USER alice SET PASSWORD 'secret';
CREATE USER alice IF NOT EXISTS SET PASSWORD 'secret';
DROP USER alice;
DROP USER alice IF EXISTS;
ALTER USER alice SET PASSWORD 'newpass';
ALTER USER alice SET STATUS SUSPENDED;
ALTER CURRENT USER SET PASSWORD 'newpass'