RETURN EXISTS { MATCH (n)-[:KNOWS]->(m) WHERE m.name = 'Alice' }
RETURN EXISTS { (n)-[:KNOWS]->() }
RETURN COUNT { MATCH (n:Person) RETURN n }
RETURN COUNT { (n)-[:KNOWS]->() }
RETURN COLLECT { MATCH (p:Person) RETURN p.name }
MATCH (n) WHERE n.name IS :: STRING RETURN n
MATCH (n) WHERE n.name IS NOT :: STRING RETURN n
MATCH (n) WHERE n IS NULL RETURN n
MATCH (n) WHERE n IS NOT NULL RETURN n
